// Generated by https://quicktype.io

export interface PDFDocument {
    status:  number;
    message: string;
    payLoad: PayLoad;
    page:    null;
}

export interface PayLoad {
    bytes:        string;
    originalName: string;
    contentType:  string;

}
